# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
baseurl: "/mohamed458.github.io"

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

# Site Settings
locale                   : "en-US"
title                    : "Samir's Blog"
title_separator          : "-"
subtitle                 : "Malware Analysis & Reverse Engineering"
name                     : "Mohamed Samir"
description              : "Malware Analysis & Reverse Engineering"
url                      : "https://abosamra0x90.github.io/mohamed458.github.io"
baseurl                  : "/mohamed458.github.io"
repository               : "mohamed458.github.io/"
teaser                   : "/assets/images/500x300.png"
logo                     : "/assets/images/site_data/logo.png"
masthead_title           : "Welcome to Mohamed Samir's Blog"
words_per_minute         : 170


comments:
  provider               : "disqus"
  disqus:
    shortname            : "samirblog"
  facebook:
    appid                : "your-facebook-app-id"
    num_posts            : 5
    colorscheme          : "light"
  utterances:
    theme                : "github-light"
    issue_term           : "pathname"
  giscus:
    repo_id              : "repo-id"
    category_name        : "General"
    category_id          : "category-id"
    discussion_term      : "pathname"
    reactions_enabled    : 1
    theme                : "light"
  staticman:
    branch               : "master"
    endpoint             : "https://{your Staticman v3 API}/v3/entry/github/"

reCaptcha:
  siteKey                : "your-recaptcha-site-key"
  secret                 : "your-recaptcha-secret-key"

atom_feed:
  path                   : "feed.xml"
  hide                   : false
search                   : true
search_full_content      : true
search_provider          : "lunr"

google:
  search_engine_id       : "your-google-search-engine-id"
  instant_search         : false

# SEO Related
google_site_verification : "your-google-site-verification-key"
bing_site_verification   : "your-bing-site-verification-key"
naver_site_verification  : "your-naver-site-verification-key"
yandex_site_verification : "your-yandex-site-verification-key"
baidu_site_verification  : "your-baidu-site-verification-key"

# Social Sharing
twitter:
  username               : "your-twitter-handle"
facebook:
  username               : "your-facebook-handle"
  app_id                 : "your-facebook-app-id"
  publisher              : "your-facebook-publisher-id"
og_image                 : "/assets/images/og-image.png"

# Social profiles
social:
  type                   : "Person"
  name                   : "Mohamed Samir"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto: mohamedayid9@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eln0ty"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/eln0ty"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohamed-ayid-42141220b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mohamed458"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eln0ty"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/eln0ty"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mohamed458"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/mohamed458"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/mohamed458"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mohamed458"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "America/New_York"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
